### PR TITLE
Added production as a synonym for prod. Updated documentation.

### PR DESCRIPTION
**Pull request by tuhlmann**

### CODE REVIEW

**Comment by dpp** [comment]
Thanks!!

**Comment by tuhlmann** [comment]
@dpp Hey David, would you mind publishing a new version to clojars that contains the pr?

**Comment by dpp** [comment]
Done... sorry for the delay: https://clojars.org/dragonmark/util/versions/0.1.4

**Comment by tuhlmann** [comment]
Thanks @dpp !

**Pull request merged**
